### ISSUE TITLE
USER STORY: Create Thank You page

### ISSUE THREAD

**Issue by JaqiKal** [VCGithubCode/Gratidudes#28]
This page will serve as feedback to the user that they have submitted their contact us form sucessfully.

**Comment by JaqiKal** [comment]
- I'm not going to style more. 
- Question that I have is  about responsiveness.  What breakpoint shall we use, only min 768px?

**Comment by VCGithubCode** [comment]
- Great question. 🙂  Once the design team has decided on whether or not to implement bootstrap, we can make a determination on the breakpoints.  For now, Patrick (who is on the design team) has stated "Just to let you guys know, if you work with css, it's mobile first approach. So first only styles that goes to mobile then if you want to style for desktop use @media query below. There is only one break point."  Whether he meant that is to be the only break point or that that is the only one he included for now, I am unsure of.  We will have to check with him in today's (Sunday) meeting to get clarification on how to proceed so that our team is in agreement and our designs are harmonious across the pages ☺️.
